video_mae_task_config:
  encoder_mask_ratio: 0.5
  pct_masks_to_decode: 0.75
  alpha: 0.5
  model_name: patch_dim_2_large

ecog_data_config:
  data_size: 1.0
  batch_size: 32
  env: false
  bands:
    - [70, 200]
  original_fs: 512
  new_fs: 256
  dataset_path: /scratch/gpfs/ln1144/ECoG-foundation-model/dataset_full
  train_data_proportion: 0.9
  sample_length: 1
  shuffle: true
  max_open_files: 45

logging_config:
  event_log_dir: event_logs
  plot_dir: plots
  print_freq: 20

trainer_config:
  max_learning_rate: 0.00001
  num_epochs: 10
  weight_decay: 0.01
  mixed_precision: 'no'
  gradient_accumulation_steps: 2


job_name: "model={}-grad_accum={}-encoder_mask_ratio={}"
format_fields: [
  video_mae_task_config.model_name,
  trainer_config.gradient_accumulation_steps,
  video_mae_task_config.encoder_mask_ratio,
]
